name: build

on:
  push:
    branches:
      - master

env:
  name: telecord

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build -c Release
      - uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          path: ./Telecord/bin/Release/net8.0
          retention-days: 1
      - uses: fjogeleit/http-request-action@v1
        with:
          url: https://torvin.one/github-deploy?repo=${{ github.repository }}&component=${{ env.name }}&artifact_id=${{ steps.upload-artifact.outputs.artifact-id }}
